# -*- coding: utf-8 -*-
"""textClassifier

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rlbZbL7tKhzn2N6KROXdJnwxTynqFRwo
"""

from transformers import pipeline

classifier = pipeline("zero-shot-classification", model="facebook/bart-large-mnli")

from transformers import pipeline

classifier = pipeline("zero-shot-classification", model="facebook/bart-large-mnli")

labels = ["English Literature", "Science", "Mathematics", "Computer Field"]

def classify_text(text, labels):
    result = classifier(text, candidate_labels=labels)
    return result

text = input("Input text: ")
result = classify_text(text, labels)
print(result["labels"])
print(result["scores"])

print(result["labels"][0])

