# # -*- coding: utf-8 -*-
# """YTVideo-Transcript.ipynb

# Automatically generated by Colab.

# Original file is located at (WITH VERSION CONTROL)
#     https://colab.research.google.com/drive/1kYn7F3GAiFO1U_cK5r3V8sOgkbq4EV-Q

# !pip install youtube_transcript_api

from math import floor

"""# YOUTUBE VIDEOS TRANSCRIPTION VIA youtube_transcript_api"""

def getText(transcript): # Get text of transcription
  text = ""
  for i in transcript:
    text += f"{i.text}\n"

  return text

def getTranscript(transcript, timestamp, showTimestamp=False): # displays the timestamp and the text
  text = ""
  if timestamp[0] == -1:
    text = getText(transcript)
    timestamp[0] = 0
    timestamp[1] = round(transcript[-1].start)
    return text, timestamp

  if timestamp[1] == -1:
    timestamp[1] = round(transcript[-1].start)


  for i in transcript:
    time = i.start    # retrieve timestamp (in sec)
    if timestamp[0] <= time <= timestamp[1]:    # retrieves only in range of the given timestamp
      if time >= 60:
        sec = str(floor(time % 60))
        if len(sec) < 2:
          sec = "0" + sec

        time = f"{str(int(time // 60))}:{sec}"
        text += f"{i.text}\n"
        if showTimestamp:
          print(f"({time})", i.text, end="\n")
        continue

      text += f"{i.text}\n"
      if showTimestamp:
        print(f"({floor(time)})", i.text, end="\n")

  return text, timestamp

from youtube_transcript_api import YouTubeTranscriptApi
ytt_api = YouTubeTranscriptApi()
timeStart, timeEnd = 0, 0
timestamp = list()

url = input("YT URL: ")


# Determine what kind of YT URL and extracts only the ID
try:    # URL link
  url.index("youtube")
  url = url[url.index("=")+1:]
except: # Share URL link
  if "t=" in url:   # extract timestamp if there's one
    timeStart = int(url[url.index("t=")+2:])

  url = url[17:url.index("?")]

if timeStart == 0:
  try:
    timeStart = int(input("Timestamp Start (in sec): "))
  except:
    timeStart = -1  # Extract all transcript

if timeStart != -1:
  try:
    timeEnd = int(input("Timestamp End (in sec): "))
  except:
    timeEnd = -1  # Extract until end

# if timeEnd < timeStart:
#   print("Invalid timestamp")

timestamp = [timeStart, timeEnd]

a = ytt_api.fetch(url)

try:
  text, timestamp = getTranscript(a, timestamp, showTimestamp=False)
except:
  text = "NO CAPTIONS AVAILABLE"

print(text)

print()
print("YouTube Video ID:", url)
print("Timestamp:", timestamp)