# # -*- coding: utf-8 -*-
# """YTVideo-Transcript.ipynb

# Automatically generated by Colab.

# Original file is located at (WITH VERSION CONTROL)
#     https://colab.research.google.com/drive/1kYn7F3GAiFO1U_cK5r3V8sOgkbq4EV-Q

# !pip install youtube_transcript_api

from math import floor
from youtube_transcript_api import YouTubeTranscriptApi
from abstractive_sum import openai_summarize
import os


"""# YOUTUBE VIDEOS TRANSCRIPTION VIA youtube_transcript_api"""

def getText(transcript): # Get text of transcription
  text = ""
  for i in transcript:
    text += f"{i.text}\n"

  return text

def getTranscriptLocal(transcript: dict, timestamp, showTimestamp=False): # displays the timestamp and the text
  text = ""
  if timestamp[0] == -1:
    text = getText(transcript)
    timestamp[0] = 0
    timestamp[1] = round(transcript[-1].start)
    return text, timestamp

  if timestamp[1] == -1:
    timestamp[1] = round(transcript[-1].start)


  for i in transcript:
    time = i.start    # retrieve timestamp (in sec)
    if timestamp[0] <= time <= timestamp[1]:    # retrieves only in range of the given timestamp
      if time >= 60:
        sec = str(floor(time % 60))
        if len(sec) < 2:
          sec = "0" + sec

        time = f"{str(int(time // 60))}:{sec}"
        text += f"{i.text}\n"
        if showTimestamp:
          print(f"({time})", i.text, end="\n")
        continue

      text += f"{i.text}\n"
      if showTimestamp:
        print(f"({floor(time)})", i.text, end="\n")

  return text, timestamp

def getTranscript(transcript: dict, timestamp, showTimestamp=False): # displays the timestamp and the text
  text = ""

  for i in transcript["snippets"]:
    time = i['start']    # retrieve timestamp (in sec)
    if timestamp[0] <= time <= timestamp[1]:    # retrieves only in range of the given timestamp
      if time >= 60:
        sec = str(floor(time % 60))
        if len(sec) < 2:
          sec = "0" + sec

        time = f"{str(int(time // 60))}:{sec}"
        text += f"{i['text']}\n"
        if showTimestamp:
          print(f"({time})", i['text'], end="\n")
        continue

      text += f"{i['text']}\n"
      if showTimestamp:
        print(f"({floor(time)})", i['text'], end="\n")

  return text

if __name__ == "__main__":
  ytt_api = YouTubeTranscriptApi()
  timeStart, timeEnd = 0, 0
  timestamp = list()

  url = input("YT URL: ")


  # Determine what kind of YT URL and extracts only the ID
  try:
    if "youtube" in url:      # URL Link
      url = url[url.index("=")+1:]
    elif "youtu.be" in url:   # Share Link
      if "t=" in url:         # with start time
        timeStart = int(url[url.index("t=")+2:])
      url = url[17:url.index("?")]
  except Exception as e:
    print("Failed fetching. Error:", e)

  # try:    # URL link
  #   url.index("youtube")
  #   url = url[url.index("=")+1:]
  # except: # Share URL link
  #   if "t=" in url:   # extract timestamp if there's one
  #     timeStart = int(url[url.index("t=")+2:])
  #   url = url[17:url.index("?")]

  if timeStart == 0:
    try:
      timeStart = int(input("Timestamp Start (in sec): "))
    except:
      timeStart = -1  # Extract all transcript

  if timeStart != -1:
    try:
      timeEnd = int(input("Timestamp End (in sec): "))
    except:
      timeEnd = -1  # Extract until end

  # if timeEnd < timeStart:
  #   print("Invalid timestamp")

  timestamp = [timeStart, timeEnd]

  
  a = ytt_api.fetch(url)

  try:
    text, timestamp = getTranscriptLocal(a, timestamp, showTimestamp=False)
  except:
    text = "NO CAPTIONS AVAILABLE"

  print(text)
  # Create a txt file with the transcript
  filename = "transcript.txt"
  with open(filename, "a", encoding="utf-8") as f:
    f.write(str(text))

  print()
  print("YouTube Video ID:", url)
  print("Timestamp:", timestamp)

  length = input("Length (1 | 2 | 3): ")
  print()
  print("Summarizing...")
  summary = openai_summarize(text, length)

  print(summary)

  # Delete transcript txt
  if os.path.exists(filename):
        os.remove(filename)